version: '3.1'

services:

  filebrowser:
    image: filebrowser/filebrowser
    restart: always
    container_name: filebrowser
    user: 1000:1000
    ports:
      - "8080:80"
    environment:
      TZ: Europe/Madrid
    volumes:
      - /home/pi/data:/srv
      - /home/pi/filebrowser/filebrowser.db:/database.db

  navidrome:
    image: deluan/navidrome:latest
    restart: always
    container_name: navidrome
    user: 1000:1000
    ports:
      - "4533:4533"
    environment:
      ND_LOGLEVEL: info
    volumes:
      - /home/pi/data:/music
      - /home/pi/navidrome/data:/data

  yt_dlp:
    image: manologcode/yt_dlp
    restart: always
    container_name: yt_dlp
    command: gunicorn wsgi:app  -w 5 -b :5000 --reload
    ports:
      - "5010:5000"
    volumes:
      - /home/pi/data/youtube_audios:/youtube_audios

  text_to_mp3:
    image: manologcode/text_to_mp3
    restart: always
    container_name: text_to_mp3
    command: gunicorn wsgi:app  -w 5 -b :5000 --reload
    ports:
      - "5020:5000"
    volumes:
      - /home/pi/data/text_audios:/text_audios

